name: Deploy on breans.jar change

on:
  push:
    branches:
      - main
    paths:
      - 'jar/breans.jar'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          settings-path: ${{ github.workspace }}

      - name: Deploy package
        run: mvn deploy -DskipTests
